spring:
  application:
    name: Ribbon-Client
    
server:
  port: 8085
      
asyoulike:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:8081,localhost:8082,localhost:8083
    ServerListRefreshInterval: 1000
   
