spring:
  application:
    name: ribbon-client
    
server:
  port: 8088
      
servise-hi:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:8082,localhost:8083,localhost:8084
    ServerListRefreshInterval: 1000